apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-practice
  labels:
    app: langchain-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain-practice
  template:
    metadata:
      labels:
        app: langchain-practice
    spec:
      containers:
      - name: langchain-practice
        image: __IMAGE__
        imagePullPolicy: Always
        command: ["python", "-m", "http.server", "8000"]
        ports:
        - containerPort: 8000
