apiVersion: v1
kind: Service
metadata:
  name: langchain-practice
  labels:
    app: langchain-practice
spec:
  type: ClusterIP
  selector:
    app: langchain-practice
  ports:
  - name: http
    port: 80
    targetPort: 8000
